version: "2"

services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - ${PORT}:9000
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      # 7.9.x only, configuration files, such as sonar.properties
      - ${OPT_PATH}/conf:/opt/sonarqube/conf
      # data files, such as the embedded H2 database and Elasticsearch indexes
      - ${OPT_PATH}/data:/opt/sonarqube/data
      # data files, such as the embedded H2 database and Elasticsearch indexes
      - ${OPT_PATH}/logs:/opt/sonarqube/logs
      # plugins, such as language analyzers
      - ${OPT_PATH}/extensions:/opt/sonarqube/extensions

  db:
    image: postgres:alpine
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ${DATA_PATH}/postgresql:/var/lib/postgresql

networks:
  sonarnet:
    driver: bridge
