version: "2"

services:
  opt:
    image: sonarqube:latest
    restart: unless-stopped
    ports:
      - ${PORT}:9000
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: ${DB_USERNAME}
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
    volumes:
      # data files, such as the embedded H2 database and Elasticsearch indexes
      - ${OPT_PATH}/data:/opt/sonarqube/data
      # plugins, such as language analyzers
      - ${OPT_PATH}/extensions:/opt/sonarqube/extensions
      # data files, such as the embedded H2 database and Elasticsearch indexes
      - ${OPT_PATH}/logs:/opt/sonarqube/logs
      - ${OPT_PATH}/temp:/opt/sonarqube/temp
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_PATH}/postgresql:/var/lib/postgresql
      - ${DATA_PATH}/postgresql/data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
